dashboard:
  states: []
  actions: []
  basicPlus: []
detailView:
  - label: Device Monitoring on/off
    displayType: switch
    switch:
      command:
        name: setSwitch
        'on': 'on'
        'off': 'off'
        argumentType: string
      state:
        value: switch.value
        valueType: string
        'on': 'Monitoring On'
        'off': 'Monitoring Off'
    state: null
automation:
  conditions: []
  actions: []
id: partyvoice23922.moncontrol
version: 1
